## Assignment 2
## Author : Raziq Ahmad Saudagar

## Task1

1. Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [1]:
def myfun():
    try:
        a= 5/0
    except :
        print("can not devide by zero")

In [2]:
myfun()

can not devide by zero


2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].  
Hint: Subject,Verb and Object should be declared in the program as shown below.  
subjects=["Americans ","Indians"]  
verbs=["play","watch"]  
objects=["Baseball","Cricket"] 

Output should come as below:  
Americans  play Baseball.  
Americans  play Cricket.  
Americans  watch Baseball.   
Americans  watch Cricket.   
Indians play Baseball.   
Indians play Cricket.   
Indians watch Baseball.   
Indians watch Cricket. 

In [6]:
subjects=["Americans ","Indians"]  
verbs=["play","watch"]  
objects=["Baseball","Cricket"] 

for sub in subjects:
    for ver in verbs:
        for obj in objects:
            print(sub+' '+ver+' '+obj)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2:

Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.   
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde.   

In [8]:
import numpy as np

In [28]:
x = np.array([1, 2, 3, 5])
y = np.array([2,4,6,8,10])

In [34]:
def myVander(x,N, incr):
    if(incr == True):
        myMatrix = np.column_stack([x**(N-1-i) for i in range(N)])
    else:
        myMatrix = np.column_stack([x**(i) for i in range(N)])
    print(myMatrix)
    
 

In [35]:
myVander(x,4,True)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [36]:
myVander(x,4,False)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [38]:
myVander(y,5,False)

[[    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]]


In [ ]:
myVander(y,5,False)

In [11]:
help(np.vander)

Help on function vander in module numpy.lib.twodim_base:

vander(x, N=None, increasing=False)
    Generate a Vandermonde matrix.
    
    The columns of the output matrix are powers of the input vector. The
    order of the powers is determined by the `increasing` boolean argument.
    Specifically, when `increasing` is False, the `i`-th output column is
    the input vector raised element-wise to the power of ``N - i - 1``. Such
    a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.
    
    Parameters
    ----------
    x : array_like
        1-D input array.
    N : int, optional
        Number of columns in the output.  If `N` is not specified, a square
        array is returned (``N = len(x)``).
    increasing : bool, optional
        Order of the powers of the columns.  If True, the powers increase
        from left to right, if False (the default) they are reversed.
    
        .. versionadded:: 1.9.0
    
    Returns
    ------